# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170916_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='thread',
        ),
    ]
