# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20170916_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titlle',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
