# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_titlle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titlle',
            new_name='title',
        ),
    ]
