# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_thread_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='board',
        ),
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.ManyToManyField(to='board.Board'),
        ),
    ]
